version: 2.1

jobs:
  build:
    docker:
      - image: circle/node:10
    branches:
      only: "master"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3a:af:54:9d:57:e4:22:f2:4f:7b:f0:5f:c6:e4:c5:67"
      - checkout
      - restore_cache:
          keys:
            - dependencies-
      - run:
          name: install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-
      - run:
          name: Build github pages
          command: npm run build
      - run:
          name: Prepare shell commands
          command: chmod +x scripts/deploy.sh
      - run:
          name: Run Deploy scripts
          command: ./scripts/deploy.sh
workflows:
  build:
    jobs:
      - build
