version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.18.1
    # branches:
    #   only: "main"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c8:bf:ed:9c:f6:b9:45:93:7d:aa:17:be:d0:06:ba:27"
      - checkout
      - restore_cache:
          keys:
            - dependencies-
      - run:
          name: install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-
      - run:
          name: Build github pages
          command: npm run build
      - run:
          name: Prepare shell commands
          command: chmod +x scripts/deploy.sh
      - run:
          name: Run Deploy scripts
          command: ./scripts/deploy.sh
workflows:
  deploy:
    jobs:
      - build
