version: 2.1

jobs:
  build:
    docker:
      - image: circle/node:18
    branches:
      only: "master"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "72:a2:03:55:34:a2:af:48:15:af:f6:ba:ba:81:d2:68"
      - checkout
      - restore_cache:
          keys:
            - dependencies-
      - run:
          name: install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-
      - run:
          name: Build github pages
          command: npm run build
      - run:
          name: Prepare shell commands
          command: chmod +x scripts/deploy.sh
      - run:
          name: Run Deploy scripts
          command: ./scripts/deploy.sh
workflows:
  build:
    jobs:
      - build
